### ISSUE TITLE
AgeTacular --> Apple iOS Data sharing

### ISSUE THREAD

**Issue by iamslappy** [cmhgit/AgeTacular#24]
Hello,
Re AgeTacular, is it possible to somehow share or copy data between my iPhone 6s Plus (iOS v10.3.3) and my iPad Air (iOS v10.3.3) so that I don't have to manually re-input each person and the data for each person. It sure would make life a little easier for such an awesome product. I use to use Age Tracker but AgeTacular is much, much better.
If I can provide any clarification, please don't hesitate to contact me.

I look forward to your kind reply.
Sincerely,
Terry

**Comment by cmhgit** [comment]
Thanks for the kind comments. I've had a couple of inquiries via email on syncing between devices as well. I've been surprised and humbled by how many events, birthdays, etc. that people are tracking in AgeTacular! I originally didn't think an iCloud sync type of solution would ever be that useful, and thought it may introduce unnecessary added complexity, but I've learned that some form of sync between devices would likely be a valued feature. It'll be my first time implementing something like this, so I do want to take my time and try to get it done right! I will keep this issue open and assign it to a milestone with a target date soon. Thanks for your patience!

**Comment by iamslappy** [comment]
Hi,
Thank you for your prompt reply!! Those comments I made were well earned and I stand behind them!! :-)

Yes, it will be a milestone in the product lifespan, and I await a target date with much patience.

Should it be of any advantage to you, I do have a great deal of beta testing experience in both the iOS and Windows platforms and offer my assistance to you should you require such assistance...

Sincerely,
Terry

|
Terry Engel
Sent via Mobile Device 1

**Comment by cmhgit** [comment]
I was hoping to leverage the iCloud Programming Guide for Core Data, but iCloud sync with CoreData Ubiquity calls get warnings now that seem to imply they will soon be deprecated. CloudKit is apparently the way to go now, but using CloudKit seems to leave sync protocols as an exercise to the developer, and a lot can go wrong with roll-your-own sync (e.g., dups, data loss, etc.). I'll plan to use this as a guide when I can get to it:

https://developer.apple.com/library/content/documentation/DataManagement/Conceptual/CloudKitQuickStart/MaintainingaLocalCacheofCloudKitRecords/MaintainingaLocalCacheofCloudKitRecords.html#//apple_ref/doc/uid/TP40014987-CH12-SW1

**Comment by cmhgit** [comment]
Feature complete and submitted to the AppStore for review.
